name: Run autotests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.28.1' # the full version of `docker-compose` command

    - uses: actions/checkout@v4

    - name: Fetch gh-pages Branch
      run: git fetch origin gh-pages

    - name: Retrieve Allure History
      run: |
        if git cat-file -e origin/gh-pages:reports/${GITHUB_REF_NAME}/history; then
          git checkout origin/gh-pages -- reports/${GITHUB_REF_NAME}/history
          mkdir -p allure-results/history
          cp -r reports/${GITHUB_REF_NAME}/history/* allure-results/history/
          echo "History folder copied!"
          ls -la allure-results/history/
        else
          echo "No history folder found for ${GITHUB_REF_NAME} in gh-pages."
        fi


    - name: Run autotests
      run: make -C qa test

    - name: Clean up
      if: always()
      run: make -C qa stop

    - name: Generate Allure Report
      if: always()
      run: make -C qa gh_report

    - name: Publish Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        destination_dir: reports/${{ github.ref_name }}
        keep_files: true

  update-index:
    name: Update Allure Index Page
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout gh-pages branch
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Generate Index Page
        if: always()
        run: |
          make -C qa gh_index

      - name: Commit and Push Updated Index
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Skipping."
          else
            git commit -am "Update Allure index page"
            git push
          fi
