name: Run autotests

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.28.1' # the full version of `docker-compose` command
    - name: Run autotests
      run: make -C qa test
    - name: Clean up
      if: always()
      run: make -C qa stop

    - name: Generate Allure Report
      if: always()
      run: make -C qa gh_report
    - name: Deploy to GitHub Pages
      if: always()
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout --orphan gh-pages
        rm -rf .github/
        mv allure-report/* ./
        git add .
        git commit -m "Deploy Allure report"
        git push -f origin gh-pages
