services:
  tests:
    build:
      context: ./../
      dockerfile: docker/tests/Dockerfile
    depends_on:
      - app
      - db
    environment:
      - HOST=app.dev.local
      - DATABASE_URL=postgresql://trader:trader@db/trader
    volumes:
      - ./../allure-results:/qa/allure-results
    command: |
      sh -c "
        timeout 10s bash -c '
        until curl -fs http://app/ping; do
          echo Waiting for the app...;
          sleep 1;
        done;
        echo The app is ready. Starting tests...;
        ' || (echo Timeout reached! The app is not ready.; exit 1)
        ./start_tests.sh
      "
