services:
  tests:
    build:
      context: ./../
      dockerfile: docker/tests/Dockerfile
    depends_on:
      - app
      - db
    environment:
      - APP_HOST=http://app.dev.local
      - DATABASE_URL=postgresql://trader:trader@db/trader
    ports:
      - "80:80"
    command: |
      sh -c "
        timeout 10s bash -c '
        until curl -fs http://app/ping; do
          echo Waiting for app...;
          sleep 1;
        done;
        echo App is ready. Starting tests...;
        ' || (echo Timeout reached! App is not ready.; exit 1)
        ./start_tests.sh
      "
